# Generated by Django 5.2.4 on 2025-08-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='tipo',
            field=models.CharField(choices=[('BW', 'Preto e branco'), ('COLOR', 'Colorida')], default='BW', max_length=10),
        ),
        migrations.CreateModel(
            name='PrinterStatusBW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_printer', models.PositiveIntegerField()),
                ('toner_printer', models.CharField(max_length=100)),
                ('unit_printer', models.CharField(max_length=100)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bw_statuses', to='api.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrinterStatusColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('toner_printer_cyan', models.CharField(max_length=100)),
                ('toner_printer_magenta', models.CharField(max_length=100)),
                ('toner_printer_yellow', models.CharField(max_length=100)),
                ('toner_printer_black', models.CharField(max_length=100)),
                ('unit_printer_cyan', models.CharField(max_length=100)),
                ('unit_printer_magenta', models.CharField(max_length=100)),
                ('unit_printer_yellow', models.CharField(max_length=100)),
                ('unit_printer_black', models.CharField(max_length=100)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_statuses', to='api.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PrinterStatus',
        ),
    ]
