# Generated by Django 5.2.4 on 2025-08-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printerstatus',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
