# Generated by Django 5.2.4 on 2025-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_printer_tipo_printerstatusbw_printerstatuscolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerstatuscolor',
            name='page_printer',
            field=models.PositiveIntegerField(default=89710),
            preserve_default=False,
        ),
    ]
